#!/usr/bin/env bash
# custom dig output

get_info() {
  domain=$1
  if [ -z $2 ]
  then
    for sub in "www" "lb-01" "web-01" "web-02"
    do
      name="$sub.$1"
      record="$(dig +noall +answer $name)"
      echo "$record" | awk -v su="$sub" '{ printf "The subdomain %s is a %s record and points to %s\n", su, $4, $5}'
    done
  else
    name="$2.$1"
    record="$(dig +noall +answer $name)"
    echo "$record" | awk -v su="$2" '{ printf "The subdomain %s is a %s record and points to %s\n", su, $4, $5}'
  fi
}

get_info $1 $2
