#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
#
#   username
#   user id
#   Home directory path for the user

exec < /etc/passwd

while read -r passwd_output ; do
	echo "$passwd_output" | cut -d':' -f1,3,6
done
